name: Docker Image CI

on:
  [workflow_dispatch]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]


jobs:

  publish_images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fntm04ka/appluni-backend:latest
    - name: push image to Dockerhub
      run: docker push fntm04ka/appluni-backend:latest
